### ISSUE TITLE
css引入问题

### ISSUE THREAD

**Issue by daidaibg** [imzbf/markdown-theme#1]
vite+ts+v3以下方式引入会报错
```css
@vavt/markdown-theme/all.css
```
![image](https://user-images.githubusercontent.com/55817318/220248680-a159c15d-e5fe-47a0-97cf-892491446695.png)

#### 加一个css路径就没事
```css
import "@vavt/markdown-theme/css/all.css";
```

**Comment by imzbf** [comment]
是的，这个库需要写全地址，没有`index`
