### ISSUE TITLE
md-editor-v3新版本样式没有集成进来

### ISSUE THREAD

**Issue by daidaibg** [imzbf/markdown-theme#2]
copy按钮样式丢失，
![image](https://user-images.githubusercontent.com/55817318/227097164-23800485-7507-4b3f-bea4-6c93d85b793c.png)

**Comment by imzbf** [comment]
这个库可能要放弃单独引入了。部分不属于主题的样式需要共享了

目前还是建议这样引用。

```js
import 'md-editor-v3/lib/style.css';
```

**Comment by daidaibg** [comment]
好的
